# ML-Fundamentals - Python Numpy Basics

## Table of Contents
* [Introduction](#Introduction)
* [Requirements](#Requirements) 
  * [Knowledge](#Knowledge) 
  * [Modules](#Python-Modules)
* [Exercises](#Exercises)
* [Summary and Outlook](#Summary-and-Outlook)
* [Literature](#Literature) 
* [Licenses](#Licenses)

## Introduction

In this exercise you will learn numpy operations / features, which you will need throughout nearly all data science tasks, when working with python.

## Requirements
### Knowledge

You should have a basic knowledge of:
- numpy

Suitable sources for acquiring this knowledge are:
- [numpy quickstart](https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html)
- [numpy slicing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)

### Python Modules

By [deep.TEACHING](https://www.deep-teaching.org/) convention, all python modules needed to run the notebook are loaded centrally at the beginning. 


In [1]:
# External Modules
import numpy as np

## Exercises

**Task:**

Generate a numpy-1D array of length 10, all elements being 0, except the 5th element which is 1

In [2]:
z = np.zeros(10) #Array aus 10 Zeichen, gefüllt mit 0
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**Task:**

Reverse the order of vector `z`: The first element becomes the last, the second becomes the second last etc.

In [3]:
z = np.arange(50) #Array im Interval von 0 bis 49
z = np.flip(z)
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


**Task:**

Find the indices of all elements that are nonzero.

In [7]:
### Your Solution
z = np.array([1,2,0,0,4,0])
z = np.argwhere(z) #Elemente, die nicht Null sind
print(z)

[[0]
 [1]
 [4]]


**Task:**

Generate a 10x10 array with random values and find the smallest and largest value.

In [5]:
m = np.random.rand(10,10)
print(np.amin(m), np.amax(m))

0.0022191959297483965 0.99676944127731


**Task:**

Generate a vector of length 50 with random values and calculate the mean.

In [6]:
### Your Solution
m = np.random.rand(50)
print(np.mean(m))

0.4854033544868669


**Task:**

Explain the following results:

In [7]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


- np.nan == np.nan => nan ist nicht gleich nan laut Definition
- 0.3 == 3 * 0.1 => hat als letzte Ziffer eine 4 und ist somit nicht gleich

**Task:**

Generate an 8x8 matrix and fill it with a chess pattern like:

`
array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])
`

In [9]:
x = np.ones((8,8),dtype=float)
x[1::2,::2] = 0
x[::2,1::2] = 0
print(x)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


**Task:**

Generate a random 5x5 matrix and normalize (scale) it. That means, the smallest value should become 0.0, the largest 1.0

In [44]:
z = np.random.rand(5,5)
z = np.sort(z)

min = np.amin(z)
max = np.amax(z)

new_matrix = []
new_row = []

for row in z:
    for item in row:
        new_row.append((item - min)/max)
    new_matrix.append(new_row)
    new_row = []
    
print(new_matrix)

[[0.06713852452574968, 0.4358766070491623, 0.44774736869845755, 0.6696889901650644, 0.8838311253775839], [0.0, 0.2918436149624788, 0.37368275717252886, 0.5197558238147809, 0.5939315901175208], [0.06498686532809138, 0.36869073402995767, 0.4767276110331727, 0.590316869090918, 0.8045807574113627], [0.11145593269056406, 0.19434801111597802, 0.1966310674197645, 0.4809887871301519, 0.6370666694317988], [0.10453375273476898, 0.19575232123034236, 0.7052639585828083, 0.7103019007264206, 0.8263595393409162]]


**Task:**

From each row, subtract the maximum value of that row.

In [33]:
z = np.random.randint(0,10, size=(3,4))
print(z)
for j in range(z.shape[0]): #Iterator über Zeilen
    max_value = np.amax(z[j])
    for i in range(z.shape[1]): #Iterator über Spalten
        z[j][i] -= max_value   
print(z)

[[8 2 8 1]
 [9 7 2 3]
 [2 7 6 9]]
[[ 0 -6  0 -7]
 [ 0 -2 -7 -6]
 [-7 -2 -3  0]]


**Task:**
    
Divide each column by the sum of that column. Then verify that each column adds up to 1.

In [11]:
### Your Solution
z = np.arange(12, dtype=float).reshape((3,4))
print(z)

sum_column = (z.sum(axis=0))

for j in range(z.shape[0]):
    for i in range(z.shape[1]):
        z[j][i] = z[j][i] / sum_column[i]
        
print(z)

sum_column = (z.sum(axis=0))
print(np.all(sum_column == 1))

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[0.         0.06666667 0.11111111 0.14285714]
 [0.33333333 0.33333333 0.33333333 0.33333333]
 [0.66666667 0.6        0.55555556 0.52380952]]
True


**Task:**

Negate all elements between 3 and 8 in place.

In [12]:
### Your Solution
Z = np.arange(11)

for i in Z:
    if Z[i] > 3 and Z[i] < 8:
        Z[i] *= (-1)
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


**Task:**

Explain the result (output) of the following code:

In [13]:
### Your Solution
print(sum(range(5),-1))
from numpy import *
print(sum(range(5), axis=-1)) # axis -1
del sum

9
10


**Task:**

Generate a random vector of length 100 and sort it.

In [14]:
m = np.random.randint(50,size=100) #50 höchster Wert
print(np.sort(m))

[ 0  1  1  1  1  2  3  3  3  3  4  5  6  6  6  6  7  9 10 11 11 11 12 13
 14 15 16 16 16 17 17 17 17 18 18 20 22 22 22 23 23 24 25 25 26 26 27 27
 28 28 28 28 28 29 29 29 29 30 30 31 31 32 32 34 34 34 35 35 35 36 36 36
 36 37 37 37 38 39 40 40 41 41 41 42 42 43 44 44 45 45 45 45 47 47 48 48
 48 49 49 49]


**Task:**

Check if two arrays are equal:

    1. All elements should be exactly the same
    2. Equality within a tolerance

In [15]:
### Your Solution
A = np.random.random((3,4))
B = A.copy()
B[1,2] = A[1,2] * 1.00000000000001

theta = 0.00000000000001
for x, y in np.nditer([A, B]):
    if(x - y) < theta:
        pass
    else:
        print("Fehler")

**Task:**

Generate (as little code as possible) the following matrix with `np.array` and save it as the variable `arr`.

\begin{bmatrix}
1 & 1 & 1 &1  &1 \\ 
1 & 2 & 1 & 1 & 1\\ 
1 & 1 & 3 & 1 & 1\\ 
1 &1  & 1 & 4 & 1
\end{bmatrix}

And calculate:
- the sum of each line
- the sum of each row

In [16]:
### Your Solution
arr = np.ones((4,5),dtype=int)
arr[1:2,1:2] = 2
arr[2:3,2:3] = 3
arr[3:4,3:4] = 4
print(arr)

[[1 1 1 1 1]
 [1 2 1 1 1]
 [1 1 3 1 1]
 [1 1 1 4 1]]


**Task:**

Generate a 2x2 matrix from `arr`: It shall consist of the 4 values when taking the values of the 2nd and 4th column of arr and the even rows.

Use different methods:
(see http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)
- integer array indexes
- slices
- boolean arrays


In [17]:
### Your Solution
new_matrix = arr[1::2,1::2]
print(new_matrix)

[[2 1]
 [1 4]]


**Task:**

(see http://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html)

Explain the following operations on `arr`

In [18]:
### Your Solution
print(arr)
print('--------1-------')
print(arr * 5.)
print('--------2-------')
print(np.arange(arr.shape[1])) #Spalten zählen und per arange als Liste ausgeben
print(arr * np.arange(arr.shape[1]))
print('--------3------')
print(arr.T * np.arange(arr.shape[0]))
print('--------4-------')
print(arr * np.arange(arr.shape[0]))

[[1 1 1 1 1]
 [1 2 1 1 1]
 [1 1 3 1 1]
 [1 1 1 4 1]]
--------1-------
[[ 5.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 15.  5.  5.]
 [ 5.  5.  5. 20.  5.]]
--------2-------
[0 1 2 3 4]
[[ 0  1  2  3  4]
 [ 0  2  2  3  4]
 [ 0  1  6  3  4]
 [ 0  1  2 12  4]]
--------3------
[[ 0  1  2  3]
 [ 0  2  2  3]
 [ 0  1  6  3]
 [ 0  1  2 12]
 [ 0  1  2  3]]
--------4-------


ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

**Task:**

Calculate the matrix-vector product (dot product) of `arr` and $v$:

with:

$
v = (1,2,3,4,5)^T
$

In [19]:
### Your Solution
v = np.arange(1,6)

print(arr.dot(v.T))

[15 17 21 27]


## Summary and Outlook

In this notebook you've picked up many of the essential numpy operations for maths and data science tasks.

The more you use the library, the more of its functionality you'll discover and its usage will grow more intuitive and familiar.

## Licenses

### Notebook License (CC-BY-SA 4.0)

*The following license applies to the complete notebook, including code cells. It does however not apply to any referenced external media (e.g., images).*

Exercise: Python Numpy Basics <br/>
by Klaus Strohmenger <br/>
is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/).<br/>
Based on a work at https://gitlab.com/deep.TEACHING.


### Code License (MIT)

*The following license only applies to code cells of the notebook.*

Copyright 2019 Klaus Strohmenger

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.